// CourtQ Pro — Philippines Configuration
const CQ_CONFIG = {
    firebaseConfig: {
        apiKey: "AIzaSyBWqvEMy-q_DJWGYhOJfHsRrFQNl3ZJK9Y",
        authDomain: "courtq-2e744.firebaseapp.com",
        projectId: "courtq-2e744",
        storageBucket: "courtq-2e744.firebasestorage.app",
        messagingSenderId: "4841304416",
        appId: "1:4841304416:web:7a26d85566af1d47d4ee05"
    },
    convenienceFee: { amount: 5, currency: 'PHP', label: 'Convenience Fee (₱5/hr)' },
    currency: { symbol: '₱', code: 'PHP', name: 'Philippine Peso' },
    timezone: 'Asia/Manila',
    utcOffset: 480,
    phone: { code: '+63', placeholder: '+63 9XX XXX XXXX', pattern: /^\+63\d{10}$/ },
    locale: 'en-PH',
    country: 'Philippines',
    payments: [
        { id: 'gcash', name: 'GCash', icon: '🟢', desc: 'Send via GCash' },
        { id: 'maya', name: 'Maya', icon: '💜', desc: 'Send via Maya' },
        { id: 'cash', name: 'Cash', icon: '💵', desc: 'Pay at venue' }
    ],
    pricing: {
        free: { name: 'Free Forever', base: 0, incl: 999, extraRate: 0, perBlock: 1, color: '#2ecc71', label: '✨ Free Forever — no setup fee, no monthly fee, no commission' }
    },
    defaultCourtRate: 500,
    placeholderName: 'Juan dela Cruz',
    placeholderPhone: '+63 912 345 6789',
    legal: {
        jurisdiction: 'Philippine courts',
        governingLaw: 'Laws of the Republic of the Philippines',
        currencyDecl: 'Philippine Peso (₱)',
        companyAddr: 'Talisay City, Cebu, Philippines',
        countryRef: 'Philippines'
    },
    translations: {
        en: {
            tagline: 'Smart venue management for pickleball & racket sports',
            courtManagement: 'Court Management', onlineBooking: 'Online Booking', posSales: 'POS & Sales',
            leaderboards: 'Leaderboards', liveTvDisplay: 'Live TV Display', mobileScoring: 'Mobile Scoring',
            openPlayEngine: 'Open Play Engine', tournamentEngine: 'Tournament Engine',
            login: 'Log In', register: 'Register', join: 'Join',
            foundersOffer: '✨ Free Forever — For All Venues',
            runVenue: 'Run your pickleball venue like a pro',
            registerYourVenue: '✅ Register Your Venue', tryDemo: '🎮 Try Demo',
            email: 'Email', password: 'Password', venueName: 'Venue Name', yourName: 'Your Name',
            mobileNumber: 'Mobile Number', atLeast6: 'At least 6 characters',
            privacyPolicy: 'Privacy Policy', termsOfService: 'Terms of Service',
            continue: 'Continue →', createAccount: 'Create Account',
            settingsNote: 'After signing up, ask your venue owner to add your email in Settings → Staff or Co-Owners.',
            venueSetup: '🏗️ Venue Setup', numberOfCourts: 'Number of Courts',
            allPremiumFeatures: '✅ All premium features included:',
            freeForMonth: 'Free Forever', submitStart: '✅ Submit & Start Free',
            thankYou: 'Thank You!', submittedVerification: 'Your venue has been submitted for verification.',
            emailConfirmation: "You'll receive an email confirmation shortly.",
            processing: 'Processing Payment...', paymentSubmitted: 'Payment Submitted!',
            bookingConfirmed: 'Booking Confirmed!', bookingNotAvailable: 'Booking Not Available',
            bookNow: '📅 Book Now', joinOpenPlay: '🏓 Join Open Play',
            pickCourt: 'Choose a Court', pickTime: 'Choose Date & Time',
            yourInfo: 'Your Information', payment: 'Payment', confirm: 'Confirm',
            available: 'Available', inPlay: 'In Play', maintenance: 'Maintenance', booked: 'Booked',
            firstName: 'First Name', lastName: 'Last Name', phone: 'Phone',
            gameType: 'Game Type', players: 'Players', specialRequests: 'Special Requests',
            singles: 'Singles', doubles: 'Doubles', private: 'Private',
            total: 'Total', payBook: '✅ Pay & Book',
            sendPayment: 'Send payment to the details below, then enter your reference number.',
            refNumber: 'Reference Number', enterRef: 'Enter your GCash/Maya reference number',
            exactAmount: 'Send the exact amount shown above. Enter the reference number after payment.',
            dashboard: 'Dashboard', courts: 'Courts', bookings: 'Bookings',
            confirmations: 'Confirmations', financials: 'Financials', history: 'History',
            tournaments: 'Tournaments', settings: 'Settings',
            totalRevenue: 'Total Revenue', netProfit: 'Net Profit', grossRevenue: 'Gross Revenue',
            totalCosts: 'Total Costs', openPlay: 'Open Play',
            score: 'Score', scoresUpdateLive: 'Scores update live on the TV display',
            noActiveGames: 'No active games right now',
            enterVenueSlug: 'Enter a venue slug in the URL',
            playerA: 'Player A', playerB: 'Player B',
            teamA: 'Team A', teamB: 'Team B', resetToZero: 'Reset to 0-0',
            noActiveSession: 'No Active Session', queue: 'Queue', recentResults: 'Recent Results',
            now: 'NOW', schedule: 'Schedule', fullscreen: 'Fullscreen', live: 'Live',
            whyCourtQ: 'Why CourtQ Pro?', pricing: 'Pricing',
            theProblem: 'The Problem', ourSolution: 'Our Solution',
            howItWorks: 'How It Works', revenueModel: 'Revenue Model',
            techStack: 'Tech Stack', marketSize: 'Market Size',
            courtRate: 'Rate per Hour (₱)',
            dropInFee: 'Drop-in Fee (₱)',
            monthlyRetainer: 'Monthly Subscription (₱)',
            amountDue: 'Amount Due (₱)',
            sendTo: 'Send to',
            number: 'Number', name: 'Name', amount: 'Amount',
            pending: 'Pending', confirmed: 'Confirmed', cancelled: 'Cancelled',
            completed: 'Completed', inProgress: 'In Progress', dropped: 'Dropped',
            bookingPayments: 'Booking Payments', dropInFees: 'Drop-in Fees',
            noCourts: 'No courts available', noBookings: 'No bookings yet',
            queueEmpty: 'Queue is empty', noFinancialData: 'No financial data',
            addCourt: '➕ Add Court', editCourt: '✏️ Edit Court', removeCourt: '🗑️ Remove Court',
            saveChanges: '💾 Save Changes', saveSettings: '💾 Save Settings',
            cancel: 'Cancel', delete: 'Delete', exportCsv: '📥 Export CSV',
            shareBookingLink: '🔗 Share Booking Online Link',
            shareTvLink: '📺 Share TV Link', shareScoringLink: '📱 Share Scoring Link',
            about: 'About', privacy: 'Privacy', terms: 'Terms', disclaimer: 'Disclaimer', contact: 'Contact',
            builtFor: 'Built with ❤️ for the Filipino pickleball community.',
            contactUs: 'Contact Us', venuePartnerships: 'Venue Partnerships',
            dataPrivacy: 'Data Privacy Requests',
            paymentMethods: 'Payment Details (for customer reference)',
            venueLogo: '🖼️ Venue Logo', financialsAccess: '🔒 Financials Access Code',
            staffManagement: '👥 Staff Management', coOwners: '👑 Co-Owners',
            allMethods: 'All Methods', touchNGo: '🟢 GCash', grabPay: '💜 Maya', cashPayment: '💵 Cash',
            sendToTnG: 'Send to GCash', sendToGrabPay: 'Send via Maya',
            openPlayFee: 'Drop-in Fee: ₱', perPlayer: 'per player', totalLabel: 'Total:',
            joinQueue: '🏓 Join Queue', openPlayMode: '▶ Open Play', scheduleSession: '📅 Schedule',
            dropInFeeLabel: 'Drop-in Fee (₱)',
            pricePerHr: '/hr', chooseCourt: 'Choose a Court', selectCourt: 'Select the court you\'d like to book.',
            chooseDateTime: 'Choose Date & Time', availableSlots: 'Available slots shown below.',
            fillDetails: 'Fill in your details to complete the booking.',
            allSlotsBooked: 'All slots are booked for this date. Try another date or court.',
            noCourtsAvailable: 'No courts available right now.',
            sendToPayment: 'Send to', referenceNumber: 'Reference Number *',
            enterRefNum: 'Enter your GCash/Maya reference number',
            submitPayment: 'Send the exact amount shown above. Enter the reference number after payment.',
            selectPaymentMethod: 'Select Payment Method:',
            back: '← Back', next: 'Next →', close: '✕ Close', done: '✅ Done',
            bookAnother: '📅 Book Another', tryAgain: '🔄 Try Again',
            paymentPending: 'Payment Submitted!', waitForConfirmation: "Don't close this page. Please wait for confirmation from Admin.",
            bookingConfirmedMsg: 'Your booking has been confirmed.',
            thankYouForBooking: 'Thank you for booking with us!',
            showBookingId: 'Please show Booking ID', atVenue: 'at the venue when you arrive.',
            beEarly: '⏰ Please be there at least 15 minutes ahead of your booking schedule.',
            sessionFull: '⚠️ Session Full', spotsAvailable: '✅ Spots available — click to join',
            ongoing: '⏳ Ongoing', joinNow: '▶ Open Play is happening now — click to join!',
            noUpcomingSessions: 'No upcoming Open Play sessions scheduled right now.',
            checkBackLater: 'Check back later or contact the venue.',
            selectSessionToJoin: 'Select a session to join. No need to book a specific court — just show up and play!',
            securedFor: 'Your spot is secured for',
            showTransaction: '📱 Show your transaction on site',
            showTransactionNote: 'Present the payment transaction details when you check in at the venue.',
            seeYouThere: '🎯 See you there!',
            noPaymentNeeded: 'No payment needed — just show up and play!',
            youAreIn: "You're In!",
            fillAllRequired: 'Fill all required fields!',
            pleaseSelectCourt: 'Please select a court!',
            pleaseSelectTime: 'Please select a time slot!',
            selectPayment: 'Select a payment method!',
            enterRefRequired: 'Enter your payment reference number!',
            cantBook: 'Cannot book — Open Play session in progress during this time.',
            slotTaken: 'Sorry, this time slot was just taken. Please choose another.',
            bookingFailed: 'Booking failed to save. Please try again or contact the venue.',
            sessionNoLongerAvailable: 'Session no longer available.',
            sessionFullOnly: 'Session full — only', spotsLeft: 'spot(s) left.',
            fillAllFields: 'Fill in all fields.',
            venueNotAvailable: 'Venue not available.',
            failedToJoin: 'Failed to join. Please try again.',
            invalidEmail: 'Enter a valid email address.',
            tempEmailNotAllowed: 'Temporary or disposable emails are not allowed. Please use your real email address.',
            mustAgree: 'You must agree to the Privacy Policy and Terms of Service.',
            wrongSomething: 'Something went wrong: ',
            enterEmailPassword: 'Enter email and password.',
            fillInAll: 'Fill in all fields.',
            passwordMinLength: 'Password must be at least 6 characters.',
            mustAgreeTerms: 'You must agree to the Privacy Policy and Terms of Service.',
            creatingAccount: 'Creating your account...',
            accountCreated: 'Account created! Ask your venue owner to add your email in Settings → Staff or Co-Owners, then log in.',
            sessionExpired: 'Session expired. Please sign up again.',
            submittingVenue: 'Submitting your venue...',
            settingThingsUp: 'Setting things up...',
            loading: 'Loading...',
            demoMode: '🔧 Demo mode — data resets periodically',
            tryCourtQ: '🎮 Try CourtQ Pro',
            tryDemoDesc: 'Enter your name and real email to try the demo.',
            startDemo: '🎮 Start Demo',
            settingUpDemo: 'Setting up your demo...',
            demoFailed: 'Demo failed: ',
            tooManyDemos: 'Too many active demos right now. Please try again later.',
            venuePendingApproval: 'Venue Pending Approval',
            pendingApprovalDesc: "Your venue has been submitted and is awaiting verification. We'll notify you via email once it's activated. This usually takes a few hours.",
            questionsEmail: 'Questions? Email',
            usedByVenues: '✅ Used by venues across the Philippines',
            integratedPayments: '✅ GCash & Maya integrated',
            staffCoowner: '✅ Staff & co-owner accounts',
            regularPrice: 'Regular', foundBy: 'Free Forever — no fees, no contract',
            thenPrice: 'Then', perMo: '/mo',
            courtsIncl: 'courts incl.',
            forExtraCourts: 'for extra courts',
            forXCourts: 'court(s)',
            freeFor1Month: 'Free Forever',
            allPremiumFromDay1: '✓ All premium features included from Day 1',
            pricePreviewRate: 'Rate:', pricePreviewTotal: 'Total:',
            paymentMethod: 'Payment Method', createBooking: '📅 Create Booking',
            upcoming: 'Upcoming', today: 'Today', tomorrow: 'Tomorrow', all: 'All',
            checkedIn: 'Checked In', pendingConfirmation: 'Pending', confirmedStatus: 'Confirmed',
            reviewPending: "Review pending bookings. Verify the customer's payment reference number, then confirm.",
            accessCodeRequired: 'Access Code Required', enterAccessCode: 'Enter the owner access code to view financials.',
            unlock: '🔓 Unlock', lock: '🔒 Lock',
            bookingsLabel: 'Bookings', utilization: 'Utilization', cancelledLabel: '% cancelled',
            prevLabel: 'prev:', peakHours: '⏰ Peak Hours', netPosition: '💰 Net Position',
            monthlyNet: '📅 Monthly Net Position', expenses: '📋 Expenses',
            transactions: '📊 Transactions', detailedBreakdown: '📈 Detailed Breakdown',
            playerRetention: '👥 Player Retention', repeatPlayers: 'Repeat Players',
            newPlayers: 'New Players', topLoyal: '🏅 Top 10 Loyal Players',
            allTime: 'All Time', thisMonth: 'This Month', thisWeek: 'This Week',
            totalVenues: 'Total Venues', activeContracts: 'Active Contracts',
            monthlyRetainers: 'Active Venues', totalDue: 'Total Due',
            devDashboard: '💻 Dev Dashboard', freeTierMonitor: '📊 Free Tier Monitor',
            liveDemoActivity: '🎮 Live Demo Activity', ownerEmails: '📧 Owner Emails',
            demoLeads: '📋 Demo Leads', announcements: '📢 Announcements',
            newTournament: '🏆 New Tournament', tournamentName: 'Tournament Name',
            format: 'Format', playersTeams: 'Players / Teams (one per line, min 4)',
            playersPerGroup: 'Players per Group', eliminationStart: 'Elimination Start Round',
            advanceFromGroups: 'Advance from Groups', courtsToUse: 'Courts to Use',
            createTournament: '🏆 Create Tournament',
            roundRobinSetup: '🔄 Round Robin Setup',
            startRoundRobin: '▶ Start Round Robin',
            aiResponse: '🔮 AI', monthlyRetainerLabel: 'Free Forever',
            addPayment: '💰 Add Payment', transactionNumber: 'Transaction Number',
            dueDate: 'Due Date', paidAt: 'Paid At', savePayment: '💾 Save Payment',
            startOpenPlay: '▶ Start Open Play Session',
            startDate: 'Start Date', endDate: 'End Date', startTime: 'Start Time', endTime: 'End Time',
            rotation: 'Rotation (min)', assignCourts: 'Assign Courts',
            scheduleOpenPlay: '📅 Schedule Open Play', maxPlayers: 'Max Players',
            fourOnFour: '4 on / 4 off', winnersSplit: 'Winners Stay & Split', roundRobin: 'Round Robin',
            loopingMode: '🔄 Looping Mode', afterGame: 'After game, all players go back to the queue',
            addToQueue: '➕ Add Player', startNow: '▶ Start Now', cancelSession: '✕ Cancel',
            groupName: 'Group Name (optional)', joinQueueAs: 'Join As',
            havePartner: '👫 I have a partner', needPartner: '🙋 I need a partner',
            partnerName: 'Partner Name', fixedTeammates: '🔒 Fixed teammates (stay together each round)',
            skillLevel: 'Skill Level', beginner: 'Beginner', intermediate: 'Intermediate',
            advanced: 'Advanced', pro: 'Pro',
            bookingDetails: '📅 Booking Details', recordResult: '🏆 Record Result',
            checkIn: '✅ Check In', editPlayers: '✏️ Edit Players',
            archiveOldData: '📦 Archive Old Data', archiveDesc: 'Archive bookings and sales older than a cutoff date. Archived data will be downloaded as CSV then removed from Firestore to save space.',
            cutoffDate: 'Cutoff Date (archives everything before this date)', irreversible: '⚠️ Irreversible',
            emailCampaign: '📧 Email Campaign', postAnnouncement: '📢 Post',
            confirmAction: '⚠️ Confirm', confirmClear: '🗑️ Clear',
            addNewCourt: '🏗️ Add New Court', courtName: 'Court Name',
            location: 'Location', surface: 'Surface', environment: 'Environment',
            outdoor: 'Outdoor', indoor: 'Indoor', color: 'Color',
            descriptionNotes: 'Description / Notes', addCourtBtn: '➕ Add Court',
            editCourtTitle: '✏️ Edit Court', saveChangesBtn: '💾 Save Changes',
            removeCourtTitle: '🗑️ Remove Court', removeCourtBtn: 'Remove Court',
            venueManagement: 'Venue Management', courtSchedule: '📅 Court Schedule',
            conflicts: '⚠️ Conflicts', newBookingAdmin: '📅 New Booking (Admin)',
            customer: 'Customer', fullName: 'Full name', court: 'Court', date: 'Date',
            duration: 'Duration', oneHour: '1 hour', twoHours: '2 hours', threeHours: '3 hours',
            lessonClinic: 'Lesson/Clinic', namesComma: 'Names separated by comma',
            filterUpcoming: 'Upcoming', filterAll: 'All',
            selectCourtLabel: 'Select court...', rate: 'Rate:', totalLabel2: 'Total:',
            accessCode: 'Access Code (4-6 digits)', shareWithOwner: 'Share this code with the venue owner to access the Financials page.',
            logoUrl: 'Logo Image URL', logoHint: 'Paste a public URL to your logo image. Recommended size: 200x200px or smaller.',
            staffAccessNote: 'Staff can access the dashboard but not Financials or Settings.',
            coownerNote: 'Co-owners have full access — Financials, Settings, Confirmations, and all dashboard features.',
            add: '+ Add', pendingVerification: '⏳ Pending Verification',
            monthlyFee: 'Subscription', ackReceipt: '📋 Acknowledgement Receipt',
            receiptNum: 'Receipt #', owner: 'Owner', status: 'Status',
        },
        fil: {
            tagline: 'Smart na pamamahala ng venue para sa pickleball at racket sports',
            courtManagement: 'Pamamahala ng Court', onlineBooking: 'Online Booking', posSales: 'POS at Benta',
            leaderboards: 'Leaderboard', liveTvDisplay: 'Live TV Display', mobileScoring: 'Mobile Scoring',
            openPlayEngine: 'Open Play Engine', tournamentEngine: 'Tournament Engine',
            login: 'Mag-log In', register: 'Mag-rehistro', join: 'Sumali',
            foundersOffer: '✨ Libre Magpakailanman — Para sa Lahat ng Venue',
            runVenue: 'Patakbuhin ang iyong pickleball venue tulad ng isang pro',
            registerYourVenue: '✅ Magrehistro ng Iyong Venue', tryDemo: '🎮 Subukan ang Demo',
            email: 'Email', password: 'Password', venueName: 'Pangalan ng Venue', yourName: 'Iyong Pangalan',
            mobileNumber: 'Mobile Number', atLeast6: 'Hindi bababa sa 6 na character',
            privacyPolicy: 'Patakaran sa Privacy', termsOfService: 'Mga Tuntunin ng Serbisyo',
            continue: 'Magpatuloy →', createAccount: 'Gumawa ng Account',
            settingsNote: 'Pagkatapos mag-sign up, hilingin sa iyong venue owner na idagdag ang iyong email sa Settings → Staff o Co-Owners.',
            allPremiumFeatures: '✅ Lahat ng premium features kasama na:',
            freeForMonth: 'Libre Magpakailanman', submitStart: '✅ Isumite at Magsimula nang Libre',
            thankYou: 'Salamat!', submittedVerification: 'Ang iyong venue ay naisumite para sa beripikasyon.',
            emailConfirmation: 'Makakatanggap ka ng email confirmation sa lalong madaling panahon.',
            processing: 'Pinoproseso ang Payment...', paymentSubmitted: 'Naipadala na ang Payment!',
            bookingConfirmed: 'Kumpirmado ang Booking!', bookingNotAvailable: 'Hindi Available ang Booking',
            bookNow: '📅 Mag-book Ngayon', joinOpenPlay: '🏓 Sumali sa Open Play',
            pickCourt: 'Pumili ng Court', pickTime: 'Pumili ng Petsa at Oras',
            yourInfo: 'Iyong Impormasyon', payment: 'Pagbabayad', confirm: 'Kumpirmahin',
            available: 'Available', inPlay: 'Nagpe-play', maintenance: 'Maintenance', booked: 'Booked',
            firstName: 'Unang Pangalan', lastName: 'Apelyido', phone: 'Telepono',
            gameType: 'Uri ng Laro', players: 'Manlalaro', specialRequests: 'Mga Espesyal na Kahilingan',
            singles: 'Singles', doubles: 'Doubles', private: 'Private',
            total: 'Kabuuan', payBook: '✅ Magbayad at Mag-book',
            sendPayment: 'Ipadala ang payment sa mga detalye sa ibaba, pagkatapos ay ilagay ang iyong reference number.',
            refNumber: 'Reference Number', enterRef: 'Ilagay ang iyong GCash/Maya reference number',
            exactAmount: 'Ipadala ang eksaktong halaga na nasa itaas. Ilagay ang reference number pagkatapos ng payment.',
            dashboard: 'Dashboard', courts: 'Courts', bookings: 'Mga Booking',
            confirmations: 'Mga Kumpirmasyon', financials: 'Pinansyal', history: 'Kasaysayan',
            tournaments: 'Mga Tournament', settings: 'Settings',
            totalRevenue: 'Kabuuang Kita', netProfit: 'Netong Kita', grossRevenue: 'Kabuuang Resibo',
            totalCosts: 'Kabuuang Gastos', openPlay: 'Open Play',
            score: 'Iskor', scoresUpdateLive: 'Ang mga iskor ay nag-u-update nang live sa TV display',
            noActiveGames: 'Walang aktibong laro ngayon',
            enterVenueSlug: 'Maglagay ng venue slug sa URL',
            playerA: 'Manlalaro A', playerB: 'Manlalaro B',
            teamA: 'Team A', teamB: 'Team B', resetToZero: 'I-reset sa 0-0',
            noActiveSession: 'Walang Aktibong Session', queue: 'Pila', recentResults: 'Mga Kamakailang Resulta',
            now: 'NGAYON', schedule: 'Iskedyul', fullscreen: 'Fullscreen', live: 'Live',
            whyCourtQ: 'Bakit CourtQ Pro?', pricing: 'Presyo',
            theProblem: 'Ang Problema', ourSolution: 'Ang Aming Solusyon',
            howItWorks: 'Paano Ito Gumagana', revenueModel: 'Modelo ng Kita',
            techStack: 'Tech Stack', marketSize: 'Laki ng Merkado',
            courtRate: 'Rate bawat Oras (₱)',
            dropInFee: 'Drop-in Fee (₱)',
            amountDue: 'Halagang Babayaran (₱)',
            sendTo: 'Ipadala sa', number: 'Numero', name: 'Pangalan', amount: 'Halaga',
            pending: 'Nakabinbin', confirmed: 'Kumpirmado', cancelled: 'Kinansela',
            completed: 'Tapos', inProgress: 'Isinasagawa', dropped: 'Binitawan',
            bookingPayments: 'Mga Pagbabayad ng Booking', dropInFees: 'Mga Drop-in Fee',
            noCourts: 'Walang available na court', noBookings: 'Wala pang booking',
            queueEmpty: 'Walang laman ang pila', noFinancialData: 'Walang data pampinansyal',
            addCourt: '➕ Magdagdag ng Court', editCourt: '✏️ I-edit ang Court', removeCourt: '🗑️ Tanggalin ang Court',
            saveChanges: '💾 I-save ang Mga Pagbabago', saveSettings: '💾 I-save ang Settings',
            cancel: 'Kanselahin', delete: 'Burahin', exportCsv: '📥 I-export ang CSV',
            shareBookingLink: '🔗 I-share ang Booking Online Link',
            shareTvLink: '📺 I-share ang TV Link', shareScoringLink: '📱 I-share ang Scoring Link',
            about: 'Tungkol', privacy: 'Privacy', terms: 'Terms', disclaimer: 'Disclaimer', contact: 'Contact',
            builtFor: 'Ginawa gamit ang ❤️ para sa Filipino pickleball community.',
            contactUs: 'Makipag-ugnayan', venuePartnerships: 'Venue Partnerships',
            dataPrivacy: 'Data Privacy Requests',
            paymentMethods: 'Payment Details (para sa customer reference)',
            venueLogo: '🖼️ Logo ng Venue', financialsAccess: '🔒 Financials Access Code',
            staffManagement: '👥 Pamamahala ng Staff', coOwners: '👑 Mga Co-Owner',
            allMethods: 'Lahat ng Paraan', touchNGo: '🟢 GCash', grabPay: '💜 Maya', cashPayment: '💵 Cash',
            sendToTnG: 'Ipadala sa GCash', sendToGrabPay: 'Ipadala sa Maya',
            openPlayFee: 'Drop-in Fee: ₱', perPlayer: 'bawat manlalaro', totalLabel: 'Kabuuan:',
            joinQueue: '🏓 Sumali sa Pila', openPlayMode: '▶ Open Play', scheduleSession: '📅 Iskedyul',
            dropInFeeLabel: 'Drop-in Fee (₱)',
            pricePerHr: '/oras', chooseCourt: 'Pumili ng Court', selectCourt: 'Piliin ang court na gusto mong i-book.',
            chooseDateTime: 'Pumili ng Petsa at Oras', availableSlots: 'Ang mga available na slot ay ipinapakita sa ibaba.',
            fillDetails: 'Ilagay ang iyong mga detalye upang makumpleto ang booking.',
            allSlotsBooked: 'Lahat ng slot ay nai-book para sa petsang ito. Subukan ang ibang petsa o court.',
            noCourtsAvailable: 'Walang available na court ngayon.',
            sendToPayment: 'Ipadala sa', referenceNumber: 'Reference Number *',
            enterRefNum: 'Ilagay ang iyong GCash/Maya reference number',
            submitPayment: 'Ipadala ang eksaktong halaga na nasa itaas. Ilagay ang reference number pagkatapos ng payment.',
            selectPaymentMethod: 'Pumili ng Paraan ng Pagbabayad:',
            back: '← Bumalik', next: 'Susunod →', close: '✕ Isara', done: '✅ Tapos',
            bookAnother: '📅 Mag-book Muli', tryAgain: '🔄 Subukan Muli',
            paymentPending: 'Naipadala na ang Payment!', waitForConfirmation: 'Huwag isara ang pahinang ito. Mangyaring maghintay ng kumpirmasyon mula sa Admin.',
            bookingConfirmedMsg: 'Ang iyong booking ay nakumpirma na.',
            thankYouForBooking: 'Salamat sa pag-book sa amin!',
            showBookingId: 'Mangyaring ipakita ang Booking ID', atVenue: 'sa venue pagdating mo.',
            beEarly: '⏰ Mangyaring pumunta nang hindi bababa sa 15 minuto bago ang iyong iskedyul ng booking.',
            sessionFull: '⚠️ Puno na ang Session', spotsAvailable: '✅ May mga available na slot — i-click para sumali',
            ongoing: '⏳ Isinasagawa', joinNow: '▶ Nagaganap ang Open Play ngayon — i-click para sumali!',
            noUpcomingSessions: 'Walang naka-iskedyul na Open Play session ngayon.',
            checkBackLater: 'Balikan mamaya o makipag-ugnayan sa venue.',
            selectSessionToJoin: 'Pumili ng session na sasalihan. Hindi na kailangang mag-book ng specific court — pumunta lang at maglaro!',
            securedFor: 'Ang iyong lugar ay secure para sa',
            showTransaction: '📱 Ipakita ang iyong transaksyon sa venue',
            showTransactionNote: 'Ipakita ang detalye ng transaksyon ng payment kapag nag-check in ka sa venue.',
            seeYouThere: '🎯 Kita tayo doon!',
            noPaymentNeeded: 'Walang kailangang payment — pumunta lang at maglaro!',
            youAreIn: 'Ikaw ay Naka-Sali Na!',
            fillAllRequired: 'Punan ang lahat ng kinakailangang field!',
            pleaseSelectCourt: 'Mangyaring pumili ng court!',
            pleaseSelectTime: 'Mangyaring pumili ng time slot!',
            selectPayment: 'Pumili ng paraan ng pagbabayad!',
            enterRefRequired: 'Ilagay ang iyong payment reference number!',
            cantBook: 'Hindi makapag-book — may nagaganap na Open Play session sa oras na ito.',
            slotTaken: 'Paumanhin, ang time slot na ito ay kinuha na. Mangyaring pumili ng iba.',
            bookingFailed: 'Nabigo ang booking. Mangyaring subukan muli o makipag-ugnayan sa venue.',
            sessionNoLongerAvailable: 'Hindi na available ang session.',
            sessionFullOnly: 'Puno ang session —', spotsLeft: 'slot(s) na lang ang natitira.',
            fillAllFields: 'Punan ang lahat ng field.',
            venueNotAvailable: 'Hindi available ang venue.',
            failedToJoin: 'Nabigong sumali. Mangyaring subukan muli.',
            invalidEmail: 'Maglagay ng wastong email address.',
            tempEmailNotAllowed: 'Hindi pinapayagan ang temporary o disposable email. Mangyaring gamitin ang iyong tunay na email address.',
            mustAgree: 'Dapat kang sumang-ayon sa Privacy Policy at Terms of Service.',
            wrongSomething: 'May mali: ',
            enterEmailPassword: 'Ilagay ang email at password.',
            fillInAll: 'Punan ang lahat ng field.',
            passwordMinLength: 'Ang password ay dapat hindi bababa sa 6 na character.',
            mustAgreeTerms: 'Dapat kang sumang-ayon sa Privacy Policy at Terms of Service.',
            creatingAccount: 'Gumagawa ng iyong account...',
            accountCreated: 'Nagawa na ang account! Hilingin sa iyong venue owner na idagdag ang iyong email sa Settings → Staff o Co-Owners, pagkatapos ay mag-log in.',
            sessionExpired: 'Nag-expire na ang session. Mangyaring mag-sign up muli.',
            submittingVenue: 'Ini-submit ang iyong venue...',
            settingThingsUp: 'Inaayos ang mga bagay...',
            loading: 'Naglo-load...',
            demoMode: '🔧 Demo mode — ang data ay nire-reset pana-panahon',
            tryCourtQ: '🎮 Subukan ang CourtQ Pro',
            tryDemoDesc: 'Ilagay ang iyong pangalan at tunay na email upang subukan ang demo.',
            startDemo: '🎮 Simulan ang Demo',
            settingUpDemo: 'Sine-set up ang iyong demo...',
            demoFailed: 'Nabigo ang demo: ',
            tooManyDemos: 'Masyadong maraming aktibong demo ngayon. Mangyaring subukan muli mamaya.',
            venuePendingApproval: 'Nakabinbin ang Pag-apruba ng Venue',
            pendingApprovalDesc: "Ang iyong venue ay naisumite at naghihintay ng beripikasyon. Ipapaalam namin sa iyo sa pamamagitan ng email kapag ito ay na-activate. Karaniwang tumatagal ito ng ilang oras.",
            questionsEmail: 'Mga Tanong? Email',
            usedByVenues: '✅ Ginagamit ng mga venue sa buong Pilipinas',
            integratedPayments: '✅ GCash at Maya integrated',
            staffCoowner: '✅ Staff at co-owner accounts',
            regularPrice: 'Regular', foundBy: 'Libre Magpakailanman — walang bayad, walang kontrata',
            thenPrice: 'Pagkatapos', perMo: '/buwan',
            courtsIncl: 'kasama ang court',
            forExtraCourts: 'para sa karagdagang court',
            forXCourts: 'court(s)',
            freeFor1Month: 'Libre Magpakailanman',
            allPremiumFromDay1: '✓ Lahat ng premium features kasama mula Day 1',
            pricePreviewRate: 'Rate:', pricePreviewTotal: 'Kabuuan:',
            paymentMethod: 'Paraan ng Pagbabayad', createBooking: '📅 Gumawa ng Booking',
            upcoming: 'Papalapit', today: 'Ngayon', tomorrow: 'Bukas', all: 'Lahat',
            checkedIn: 'Naka-check In', pendingConfirmation: 'Nakabinbin', confirmedStatus: 'Kumpirmado',
            reviewPending: 'Suriin ang mga nakabinbing booking. I-verify ang reference number ng payment ng customer, pagkatapos ay kumpirmahin.',
            accessCodeRequired: 'Kinakailangan ang Access Code', enterAccessCode: 'Ilagay ang owner access code upang makita ang pinansyal.',
            unlock: '🔓 Buksan', lock: '🔒 Isara',
            bookingsLabel: 'Mga Booking', utilization: 'Paggamit', cancelledLabel: '% nakansela',
            prevLabel: 'dati:', peakHours: '⏰ Mga Oras ng Rurok', netPosition: '💰 Netong Posisyon',
            monthlyNet: '📅 Buwanang Netong Posisyon', expenses: '📋 Mga Gastos',
            transactions: '📊 Mga Transaksyon', detailedBreakdown: '📈 Detalyadong Breakdown',
            playerRetention: '👥 Pagpapanatili ng Manlalaro', repeatPlayers: 'Mga Paulit-ulit na Manlalaro',
            newPlayers: 'Mga Bagong Manlalaro', topLoyal: '🏅 Top 10 na Tapat na Manlalaro',
            allTime: 'Lahat ng Panahon', thisMonth: 'Ngayong Buwan', thisWeek: 'Ngayong Linggo',
            totalVenues: 'Kabuuang Venue', activeContracts: 'Aktibong Kontrata',
            monthlyRetainers: 'Aktibong Venue', totalDue: 'Kabuuang Dapat Bayaran',
            devDashboard: '💻 Dev Dashboard', freeTierMonitor: '📊 Free Tier Monitor',
            liveDemoActivity: '🎮 Live Demo Activity', ownerEmails: '📧 Mga Email ng May-ari',
            demoLeads: '📋 Demo Leads', announcements: '📢 Mga Anunsyo',
            newTournament: '🏆 Bagong Tournament', tournamentName: 'Pangalan ng Tournament',
            format: 'Format', playersTeams: 'Manlalaro / Team (isa bawat linya, min 4)',
            playersPerGroup: 'Manlalaro bawat Group', eliminationStart: 'Elimination Start Round',
            advanceFromGroups: 'Sumulong mula sa Groups', courtsToUse: 'Mga Court na Gagamitin',
            createTournament: '🏆 Gumawa ng Tournament',
            roundRobinSetup: '🔄 Round Robin Setup',
            startRoundRobin: '▶ Simulan ang Round Robin',
            aiResponse: '🔮 AI', monthlyRetainerLabel: 'Libre Magpakailanman',
            addPayment: '💰 Magdagdag ng Payment', transactionNumber: 'Transaction Number',
            dueDate: 'Due Date', paidAt: 'Binayaran Noong', savePayment: '💾 I-save ang Payment',
            startOpenPlay: '▶ Simulan ang Open Play Session',
            startDate: 'Start Date', endDate: 'End Date', startTime: 'Start Time', endTime: 'End Time',
            rotation: 'Rotation (min)', assignCourts: 'Assign Courts',
            scheduleOpenPlay: '📅 I-iskedyul ang Open Play', maxPlayers: 'Max Players',
            fourOnFour: '4 pasok / 4 labas', winnersSplit: 'Manalo Manatili at Hati',
            roundRobin: 'Round Robin',
            loopingMode: '🔄 Looping Mode', afterGame: 'Pagkatapos ng laro, lahat ng manlalaro ay babalik sa pila',
            addToQueue: '➕ Magdagdag ng Manlalaro', startNow: '▶ Simulan Ngayon', cancelSession: '✕ Kanselahin',
            groupName: 'Pangalan ng Group (opsyonal)', joinQueueAs: 'Sumali Bilang',
            havePartner: '👫 May kasama akong partner', needPartner: '🙋 Kailangan ko ng partner',
            partnerName: 'Pangalan ng Partner', fixedTeammates: '🔒 Fixed teammates (manatili nang magkasama bawat round)',
            skillLevel: 'Antas ng Kasanayan', beginner: 'Beginner', intermediate: 'Intermediate',
            advanced: 'Advanced', pro: 'Pro',
            bookingDetails: '📅 Detalye ng Booking', recordResult: '🏆 Itala ang Resulta',
            checkIn: '✅ Mag-check In', editPlayers: '✏️ I-edit ang Manlalaro',
            archiveOldData: '📦 I-archive ang Lumang Data',
            add: '+ Magdagdag', pendingVerification: '⏳ Nakabinbing Beripikasyon',
            monthlyFee: 'Subscription',
            receiptNum: 'Resibo #', owner: 'May-ari', status: 'Status',
        }
    }
};

// Helper functions
function cqFixImgurUrl(url){
    if(!url || typeof url !== 'string') return url;
    if(!url.includes('imgur.com/') || url.includes('i.imgur.com/')) return url;
    return url.replace(/https?:\/\/(www\.)?imgur\.com\//,'https://i.imgur.com/').split('?')[0].split('#')[0];
}
function cqFormatCurrency(amount) {
    return '₱' + Number(amount || 0).toLocaleString();
}
function cqNow() {
    const d = new Date();
    return new Date(d.getTime() + (d.getTimezoneOffset() + CQ_CONFIG.utcOffset) * 60000);
}
function cqTodayISO() {
    const d = cqNow();
    return d.toISOString().split('T')[0];
}
function cqTimeStr() {
    return new Date().toLocaleString('en-US', { timeZone: CQ_CONFIG.timezone });
}
let _cqLang = localStorage.getItem('cqLang') || 'en';
function t(key) {
    return (CQ_CONFIG.translations[_cqLang] && CQ_CONFIG.translations[_cqLang][key]) || CQ_CONFIG.translations.en[key] || key;
}
function setLang(lang) {
    _cqLang = lang;
    localStorage.setItem('cqLang', lang);
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        el.textContent = t(key);
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        el.placeholder = t(el.getAttribute('data-i18n-placeholder'));
    });
}
