// CourtQ Pro — Malaysia Configuration
const CQ_CONFIG = {
    convenienceFee: { amount: 15, currency: 'PHP', label: 'Convenience Fee' },
    currency: { symbol: 'RM', code: 'MYR', name: 'Malaysian Ringgit' },
    timezone: 'Asia/Kuala_Lumpur',
    utcOffset: 480,
    phone: { code: '+60', placeholder: '+60 1X XXX XXXX', pattern: /^\+60\d{9,10}$/ },
    locale: 'en-MY',
    country: 'Malaysia',
    payments: [
        { id: 'touchngo', name: "Touch 'n Go", icon: '🟢', desc: 'Send via TnG eWallet' },
        { id: 'grabpay', name: 'GrabPay', icon: '🟢', desc: 'Send via GrabPay' },
        { id: 'fpx', name: 'FPX', icon: '🏦', desc: 'Online Banking (FPX)' },
        { id: 'cash', name: 'Cash', icon: '💵', desc: 'Pay at venue' }
    ],
    pricing: {
        founding: { name: 'Founders Plan', base: 49, incl: 5, extraRate: 30, perBlock: 3, color: '#e74c3c', label: "🔥 Founders Plan — first 20: RM49/mo (regular RM59/mo)" },
        regular: { name: 'Regular Plan', base: 59, incl: 5, extraRate: 30, perBlock: 3, color: '#3498db', label: 'Regular Plan: RM59/mo' }
    },
    defaultCourtRate: 35,
    placeholderName: 'Ahmad bin Abdullah',
    placeholderPhone: '+60 12 345 6789',
    legal: {
        jurisdiction: 'Malaysian courts',
        governingLaw: 'Laws of Malaysia',
        currencyDecl: 'Malaysian Ringgit (RM)',
        companyAddr: 'Kuala Lumpur, Malaysia',
        countryRef: 'Malaysia'
    },
    translations: {
        en: {
            tagline: 'Smart venue management for pickleball & racket sports',
            courtManagement: 'Court Management', onlineBooking: 'Online Booking', posSales: 'POS & Sales',
            leaderboards: 'Leaderboards', liveTvDisplay: 'Live TV Display', mobileScoring: 'Mobile Scoring',
            openPlayEngine: 'Open Play Engine', tournamentEngine: 'Tournament Engine',
            login: 'Log In', register: 'Register', join: 'Join',
            foundersOffer: '🔥 Founders Offer — First 20 Venues',
            runVenue: 'Run your pickleball venue like a pro',
            registerYourVenue: '✅ Register Your Venue', tryDemo: '🎮 Try Demo',
            email: 'Email', password: 'Password', venueName: 'Venue Name', yourName: 'Your Name',
            mobileNumber: 'Mobile Number', atLeast6: 'At least 6 characters',
            privacyPolicy: 'Privacy Policy', termsOfService: 'Terms of Service',
            continue: 'Continue →', createAccount: 'Create Account',
            settingsNote: 'After signing up, ask your venue owner to add your email in Settings → Staff or Co-Owners.',
            venueSetup: '🏗️ Venue Setup', numberOfCourts: 'Number of Courts',
            allPremiumFeatures: '✅ All premium features included from Day 1:',
            freeForMonth: 'FREE for 1 month', submitStart: '✅ Submit & Start Free Month',
            thankYou: 'Thank You!', submittedVerification: 'Your venue has been submitted for verification.',
            emailConfirmation: "You'll receive an email confirmation shortly.",
            processing: 'Processing Payment...', paymentSubmitted: 'Payment Submitted!',
            bookingConfirmed: 'Booking Confirmed!', bookingNotAvailable: 'Booking Not Available',
            bookNow: '📅 Book Now', joinOpenPlay: '🏓 Join Open Play',
            pickCourt: 'Choose a Court', pickTime: 'Choose Date & Time',
            yourInfo: 'Your Information', payment: 'Payment', confirm: 'Confirm',
            available: 'Available', inPlay: 'In Play', maintenance: 'Maintenance', booked: 'Booked',
            firstName: 'First Name', lastName: 'Last Name', phone: 'Phone',
            gameType: 'Game Type', players: 'Players', specialRequests: 'Special Requests',
            singles: 'Singles', doubles: 'Doubles', private: 'Private',
            total: 'Total', payBook: '✅ Pay & Book',
            sendPayment: 'Send payment to the details below, then enter your reference number.',
            refNumber: 'Reference Number', enterRef: 'Enter your TnG/GrabPay/FPX reference number',
            exactAmount: 'Send the exact amount shown above. Enter the reference number after payment.',
            dashboard: 'Dashboard', courts: 'Courts', bookings: 'Bookings',
            confirmations: 'Confirmations', financials: 'Financials', history: 'History',
            tournaments: 'Tournaments', settings: 'Settings',
            totalRevenue: 'Total Revenue', netProfit: 'Net Profit', grossRevenue: 'Gross Revenue',
            totalCosts: 'Total Costs', openPlay: 'Open Play',
            score: 'Score', scoresUpdateLive: 'Scores update live on the TV display',
            noActiveGames: 'No active games right now',
            enterVenueSlug: 'Enter a venue slug in the URL',
            playerA: 'Player A', playerB: 'Player B',
            teamA: 'Team A', teamB: 'Team B', resetToZero: 'Reset to 0-0',
            noActiveSession: 'No Active Session', queue: 'Queue', recentResults: 'Recent Results',
            now: 'NOW', schedule: 'Schedule', fullscreen: 'Fullscreen', live: 'Live',
            whyCourtQ: 'Why CourtQ Pro?', pricing: 'Pricing',
            theProblem: 'The Problem', ourSolution: 'Our Solution',
            howItWorks: 'How It Works', revenueModel: 'Revenue Model',
            techStack: 'Tech Stack', marketSize: 'Market Size',
            courtRate: 'Rate per Hour (RM)',
            dropInFee: 'Drop-in Fee (RM)',
            monthlyRetainer: 'Monthly Retainer (RM)',
            amountDue: 'Amount Due (RM)',
            sendTo: 'Send to',
            number: 'Number', name: 'Name', amount: 'Amount',
            pending: 'Pending', confirmed: 'Confirmed', cancelled: 'Cancelled',
            completed: 'Completed', inProgress: 'In Progress', dropped: 'Dropped',
            bookingPayments: 'Booking Payments', dropInFees: 'Drop-in Fees',
            noCourts: 'No courts available', noBookings: 'No bookings yet',
            queueEmpty: 'Queue is empty', noFinancialData: 'No financial data',
            addCourt: '➕ Add Court', editCourt: '✏️ Edit Court', removeCourt: '🗑️ Remove Court',
            saveChanges: '💾 Save Changes', saveSettings: '💾 Save Settings',
            cancel: 'Cancel', delete: 'Delete', exportCsv: '📥 Export CSV',
            shareBookingLink: '🔗 Share Booking Online Link',
            shareTvLink: '📺 Share TV Link', shareScoringLink: '📱 Share Scoring Link',
            about: 'About', privacy: 'Privacy', terms: 'Terms', disclaimer: 'Disclaimer', contact: 'Contact',
            builtFor: 'Built with ❤️ for the Malaysian pickleball community.',
            contactUs: 'Contact Us', venuePartnerships: 'Venue Partnerships',
            dataPrivacy: 'Data Privacy Requests',
            paymentMethods: 'Payment Details (for customer reference)',
            venueLogo: '🖼️ Venue Logo', financialsAccess: '🔒 Financials Access Code',
            staffManagement: '👥 Staff Management', coOwners: '👑 Co-Owners',
            allMethods: 'All Methods', touchNGo: "🟢 Touch'n Go", grabPay: '🟢 GrabPay', fpx: '🏦 FPX', cashPayment: '💵 Cash',
            sendToTnG: "Send to Touch 'n Go", sendToGrabPay: 'Send via GrabPay', sendViaFpx: 'Pay via FPX',
            openPlayFee: 'Drop-in Fee: RM', perPlayer: 'per player', totalLabel: 'Total:',
            joinQueue: '🏓 Join Queue', openPlayMode: '▶ Open Play', scheduleSession: '📅 Schedule',
            dropInFeeLabel: 'Drop-in Fee (RM)',
            pricePerHr: '/hr', chooseCourt: 'Choose a Court', selectCourt: 'Select the court you\'d like to book.',
            chooseDateTime: 'Choose Date & Time', availableSlots: 'Available slots shown below.',
            fillDetails: 'Fill in your details to complete the booking.',
            allSlotsBooked: 'All slots are booked for this date. Try another date or court.',
            noCourtsAvailable: 'No courts available right now.',
            sendToPayment: 'Send to', referenceNumber: 'Reference Number *',
            enterRefNum: 'Enter your TnG/GrabPay/FPX reference number',
            submitPayment: 'Send the exact amount shown above. Enter the reference number after payment.',
            selectPaymentMethod: 'Select Payment Method:',
            back: '← Back', next: 'Next →', close: '✕ Close', done: '✅ Done',
            bookAnother: '📅 Book Another', tryAgain: '🔄 Try Again',
            paymentPending: 'Payment Submitted!', waitForConfirmation: "Don't close this page. Please wait for confirmation from Admin.",
            bookingConfirmedMsg: 'Your booking has been confirmed.',
            thankYouForBooking: 'Thank you for booking with us!',
            showBookingId: 'Please show Booking ID', atVenue: 'at the venue when you arrive.',
            beEarly: '⏰ Please be there at least 15 minutes ahead of your booking schedule.',
            sessionFull: '⚠️ Session Full', spotsAvailable: '✅ Spots available — click to join',
            ongoing: '⏳ Ongoing', joinNow: '▶ Open Play is happening now — click to join!',
            noUpcomingSessions: 'No upcoming Open Play sessions scheduled right now.',
            checkBackLater: 'Check back later or contact the venue.',
            selectSessionToJoin: 'Select a session to join. No need to book a specific court — just show up and play!',
            securedFor: 'Your spot is secured for',
            showTransaction: '📱 Show your transaction on site',
            showTransactionNote: 'Present the payment transaction details when you check in at the venue.',
            seeYouThere: '🎯 See you there!',
            noPaymentNeeded: 'No payment needed — just show up and play!',
            youAreIn: "You're In!",
            fillAllRequired: 'Fill all required fields!',
            pleaseSelectCourt: 'Please select a court!',
            pleaseSelectTime: 'Please select a time slot!',
            selectPayment: 'Select a payment method!',
            enterRefRequired: 'Enter your payment reference number!',
            cantBook: 'Cannot book — Open Play session in progress during this time.',
            slotTaken: 'Sorry, this time slot was just taken. Please choose another.',
            bookingFailed: 'Booking failed to save. Please try again or contact the venue.',
            sessionNoLongerAvailable: 'Session no longer available.',
            sessionFullOnly: 'Session full — only', spotsLeft: 'spot(s) left.',
            fillAllFields: 'Fill in all fields.',
            venueNotAvailable: 'Venue not available.',
            failedToJoin: 'Failed to join. Please try again.',
            invalidEmail: 'Enter a valid email address.',
            tempEmailNotAllowed: 'Temporary or disposable emails are not allowed. Please use your real email address.',
            mustAgree: 'You must agree to the Privacy Policy and Terms of Service.',
            wrongSomething: 'Something went wrong: ',
            enterEmailPassword: 'Enter email and password.',
            fillInAll: 'Fill in all fields.',
            passwordMinLength: 'Password must be at least 6 characters.',
            mustAgreeTerms: 'You must agree to the Privacy Policy and Terms of Service.',
            creatingAccount: 'Creating your account...',
            accountCreated: 'Account created! Ask your venue owner to add your email in Settings → Staff or Co-Owners, then log in.',
            sessionExpired: 'Session expired. Please sign up again.',
            submittingVenue: 'Submitting your venue...',
            settingThingsUp: 'Setting things up...',
            loading: 'Loading...',
            demoMode: '🔧 Demo mode — data resets periodically',
            tryCourtQ: '🎮 Try CourtQ Pro',
            tryDemoDesc: 'Enter your name and real email to try the demo.',
            startDemo: '🎮 Start Demo',
            settingUpDemo: 'Setting up your demo...',
            demoFailed: 'Demo failed: ',
            tooManyDemos: 'Too many active demos right now. Please try again later.',
            venuePendingApproval: 'Venue Pending Approval',
            pendingApprovalDesc: "Your venue has been submitted and is awaiting verification. We'll notify you via email once it's activated. This usually takes a few hours.",
            questionsEmail: 'Questions? Email',
            usedByVenues: '✅ Used by venues across Malaysia',
            integratedPayments: '✅ TnG & GrabPay integrated',
            staffCoowner: '✅ Staff & co-owner accounts',
            regularPrice: 'Regular', found by: 'Founders Plan — first 20 court owners',
            thenPrice: 'Then', perMo: '/mo',
            courtsIncl: 'courts incl.',
            forExtraCourts: 'for extra courts',
            forXCourts: 'court(s)',
            freeFor1Month: 'FREE for 1 month',
            allPremiumFromDay1: '✓ All premium features included from Day 1',
            pricePreviewRate: 'Rate:', pricePreviewTotal: 'Total:',
            paymentMethod: 'Payment Method', createBooking: '📅 Create Booking',
            upcoming: 'Upcoming', today: 'Today', tomorrow: 'Tomorrow', all: 'All',
            checkedIn: 'Checked In', pendingConfirmation: 'Pending', confirmedStatus: 'Confirmed',
            reviewPending: "Review pending bookings. Verify the customer's payment reference number, then confirm.",
            accessCodeRequired: 'Access Code Required', enterAccessCode: 'Enter the owner access code to view financials.',
            unlock: '🔓 Unlock', lock: '🔒 Lock',
            bookingsLabel: 'Bookings', utilization: 'Utilization', cancelledLabel: '% cancelled',
            prevLabel: 'prev:', peakHours: '⏰ Peak Hours', netPosition: '💰 Net Position',
            monthlyNet: '📅 Monthly Net Position', expenses: '📋 Expenses',
            transactions: '📊 Transactions', detailedBreakdown: '📈 Detailed Breakdown',
            playerRetention: '👥 Player Retention', repeatPlayers: 'Repeat Players',
            newPlayers: 'New Players', topLoyal: '🏅 Top 10 Loyal Players',
            allTime: 'All Time', thisMonth: 'This Month', thisWeek: 'This Week',
            totalVenues: 'Total Venues', activeContracts: 'Active Contracts',
            monthlyRetainers: 'Monthly Retainers', totalDue: 'Total Due',
            devDashboard: '💻 Dev Dashboard', freeTierMonitor: '📊 Free Tier Monitor',
            liveDemoActivity: '🎮 Live Demo Activity', ownerEmails: '📧 Owner Emails',
            demoLeads: '📋 Demo Leads', announcements: '📢 Announcements',
            newTournament: '🏆 New Tournament', tournamentName: 'Tournament Name',
            format: 'Format', playersTeams: 'Players / Teams (one per line, min 4)',
            playersPerGroup: 'Players per Group', eliminationStart: 'Elimination Start Round',
            advanceFromGroups: 'Advance from Groups', courtsToUse: 'Courts to Use',
            createTournament: '🏆 Create Tournament',
            roundRobinSetup: '🔄 Round Robin Setup',
            startRoundRobin: '▶ Start Round Robin',
            aiResponse: '🔮 AI', monthlyRetainerLabel: 'Monthly Retainer (RM)',
            addPayment: '💰 Add Payment', transactionNumber: 'Transaction Number',
            dueDate: 'Due Date', paidAt: 'Paid At', savePayment: '💾 Save Payment',
            startOpenPlay: '▶ Start Open Play Session',
            startDate: 'Start Date', endDate: 'End Date', startTime: 'Start Time', endTime: 'End Time',
            rotation: 'Rotation (min)', assignCourts: 'Assign Courts',
            scheduleOpenPlay: '📅 Schedule Open Play', maxPlayers: 'Max Players',
            fourOnFour: '4 on / 4 off', winnersSplit: 'Winners Stay & Split', roundRobin: 'Round Robin',
            loopingMode: '🔄 Looping Mode', afterGame: 'After game, all players go back to the queue',
            addToQueue: '➕ Add Player', startNow: '▶ Start Now', cancelSession: '✕ Cancel',
            groupName: 'Group Name (optional)', joinQueueAs: 'Join As',
            havePartner: '👫 I have a partner', needPartner: '🙋 I need a partner',
            partnerName: 'Partner Name', fixedTeammates: '🔒 Fixed teammates (stay together each round)',
            skillLevel: 'Skill Level', beginner: 'Beginner', intermediate: 'Intermediate',
            advanced: 'Advanced', pro: 'Pro',
            bookingDetails: '📅 Booking Details', recordResult: '🏆 Record Result',
            checkIn: '✅ Check In', editPlayers: '✏️ Edit Players',
            archiveOldData: '📦 Archive Old Data', archiveDesc: 'Archive bookings and sales older than a cutoff date. Archived data will be downloaded as CSV then removed from Firestore to save space.',
            cutoffDate: 'Cutoff Date (archives everything before this date)', irreversible: '⚠️ Irreversible',
            emailCampaign: '📧 Email Campaign', postAnnouncement: '📢 Post',
            confirmAction: '⚠️ Confirm', confirmClear: '🗑️ Clear',
            addNewCourt: '🏗️ Add New Court', courtName: 'Court Name',
            location: 'Location', surface: 'Surface', environment: 'Environment',
            outdoor: 'Outdoor', indoor: 'Indoor', color: 'Color',
            descriptionNotes: 'Description / Notes', addCourtBtn: '➕ Add Court',
            editCourtTitle: '✏️ Edit Court', saveChangesBtn: '💾 Save Changes',
            removeCourtTitle: '🗑️ Remove Court', removeCourtBtn: 'Remove Court',
            venueManagement: 'Venue Management', courtSchedule: '📅 Court Schedule',
            conflicts: '⚠️ Conflicts', newBookingAdmin: '📅 New Booking (Admin)',
            customer: 'Customer', fullName: 'Full name', court: 'Court', date: 'Date',
            duration: 'Duration', oneHour: '1 hour', twoHours: '2 hours', threeHours: '3 hours',
            lessonClinic: 'Lesson/Clinic', namesComma: 'Names separated by comma',
            filterUpcoming: 'Upcoming', filterAll: 'All',
            selectCourtLabel: 'Select court...', rate: 'Rate:', totalLabel2: 'Total:',
            accessCode: 'Access Code (4-6 digits)', shareWithOwner: 'Share this code with the venue owner to access the Financials page.',
            logoUrl: 'Logo Image URL', logoHint: 'Paste a public URL to your logo image. Recommended size: 200x200px or smaller.',
            staffAccessNote: 'Staff can access the dashboard but not Financials or Settings.',
            coownerNote: 'Co-owners have full access — Financials, Settings, Confirmations, and all dashboard features.',
            add: '+ Add', pendingVerification: '⏳ Pending Verification',
            monthlyFee: 'Monthly Fee', ackReceipt: '📋 Acknowledgement Receipt',
            receiptNum: 'Receipt #', owner: 'Owner', status: 'Status',
        },
        ms: {
            tagline: 'Pengurusan venue pintar untuk pickleball & sukan raket',
            courtManagement: 'Pengurusan Court', onlineBooking: 'Tempahan Dalam Talian', posSales: 'POS & Jualan',
            leaderboards: 'Papan Kedudukan', liveTvDisplay: 'Paparan TV Langsung', mobileScoring: 'Pemarkahan Mudah Alih',
            openPlayEngine: 'Enjin Open Play', tournamentEngine: 'Enjin Kejohanan',
            login: 'Log Masuk', register: 'Daftar', join: 'Sertai',
            foundersOffer: '🔥 Tawaran Pengasas — 20 Venue Pertama',
            runVenue: 'Urus venue pickleball anda seperti pro',
            registerYourVenue: '✅ Daftar Venue Anda', tryDemo: '🎮 Cuba Demo',
            email: 'E-mel', password: 'Kata Laluan', venueName: 'Nama Venue', yourName: 'Nama Anda',
            mobileNumber: 'Nombor Mudah Alih', atLeast6: 'Sekurang-kurangnya 6 aksara',
            privacyPolicy: 'Polisi Privasi', termsOfService: 'Syarat Perkhidmatan',
            continue: 'Teruskan →', createAccount: 'Cipta Akaun',
            settingsNote: 'Selepas mendaftar, minta pemilik venue menambah e-mel anda dalam Tetapan → Staf atau Pemilik Bersama.',
            venueSetup: '🏗️ Persediaan Venue', numberOfCourts: 'Bilangan Court',
            allPremiumFeatures: '✅ Semua ciri premium termasuk dari Hari 1:',
            freeForMonth: 'PERCUMA untuk 1 bulan', submitStart: '✅ Hantar & Mula Bulan Percuma',
            thankYou: 'Terima Kasih!', submittedVerification: 'Venue anda telah dihantar untuk pengesahan.',
            emailConfirmation: 'Anda akan menerima pengesahan e-mel tidak lama lagi.',
            processing: 'Memproses Pembayaran...', paymentSubmitted: 'Pembayaran Dihantar!',
            bookingConfirmed: 'Tempahan Disahkan!', bookingNotAvailable: 'Tempahan Tidak Tersedia',
            bookNow: '📅 Tempah Sekarang', joinOpenPlay: '🏓 Sertai Open Play',
            pickCourt: 'Pilih Court', pickTime: 'Pilih Tarikh & Masa',
            yourInfo: 'Maklumat Anda', payment: 'Pembayaran', confirm: 'Sahkan',
            available: 'Tersedia', inPlay: 'Sedang Bermain', maintenance: 'Penyelenggaraan', booked: 'Ditempah',
            firstName: 'Nama Pertama', lastName: 'Nama Akhir', phone: 'Telefon',
            gameType: 'Jenis Permainan', players: 'Pemain', specialRequests: 'Permintaan Khas',
            singles: 'Tunggal', doubles: 'Beregu', private: 'Persendirian',
            total: 'Jumlah', payBook: '✅ Bayar & Tempah',
            sendPayment: 'Hantar pembayaran ke butiran di bawah, kemudian masukkan nombor rujukan anda.',
            refNumber: 'Nombor Rujukan', enterRef: 'Masukkan nombor rujukan TnG/GrabPay/FPX anda',
            exactAmount: 'Hantar jumlah tepat di atas. Masukkan nombor rujukan selepas pembayaran.',
            dashboard: 'Papan Pemuka', courts: 'Court', bookings: 'Tempahan',
            confirmations: 'Pengesahan', financials: 'Kewangan', history: 'Sejarah',
            tournaments: 'Kejohanan', settings: 'Tetapan',
            totalRevenue: 'Jumlah Pendapatan', netProfit: 'Untung Bersih', grossRevenue: 'Pendapatan Kasar',
            totalCosts: 'Jumlah Kos', openPlay: 'Open Play',
            score: 'Markah', scoresUpdateLive: 'Markah dikemaskini secara langsung pada paparan TV',
            noActiveGames: 'Tiada permainan aktif sekarang',
            enterVenueSlug: 'Masukkan slug venue dalam URL',
            playerA: 'Pemain A', playerB: 'Pemain B',
            teamA: 'Pasukan A', teamB: 'Pasukan B', resetToZero: 'Set semula ke 0-0',
            noActiveSession: 'Tiada Sesi Aktif', queue: 'Baris Gilir', recentResults: 'Keputusan Terkini',
            now: 'SEKARANG', schedule: 'Jadual', fullscreen: 'Skrin Penuh', live: 'LANGSUNG',
            whyCourtQ: 'Mengapa CourtQ Pro?', pricing: 'Harga',
            theProblem: 'Masalah', ourSolution: 'Penyelesaian Kami',
            howItWorks: 'Cara Berfungsi', revenueModel: 'Model Pendapatan',
            techStack: 'Stack Teknologi', marketSize: 'Saiz Pasaran',
            courtRate: 'Kadar Sejam (RM)',
            dropInFee: 'Fi Drop-in (RM)',
            monthlyRetainer: 'Retainer Bulanan (RM)',
            amountDue: 'Jumlah Dibiayai (RM)',
            sendTo: 'Hantar ke',
            number: 'Nombor', name: 'Nama', amount: 'Jumlah',
            pending: 'Menunggu', confirmed: 'Disahkan', cancelled: 'Dibatalkan',
            completed: 'Selesai', inProgress: 'Sedang Berjalan', dropped: 'Ditinggalkan',
            bookingPayments: 'Pembayaran Tempahan', dropInFees: 'Fi Drop-in',
            noCourts: 'Tiada court tersedia', noBookings: 'Belum ada tempahan',
            queueEmpty: 'Baris gilir kosong', noFinancialData: 'Tiada data kewangan',
            addCourt: '➕ Tambah Court', editCourt: '✏️ Edit Court', removeCourt: '🗑️ Buang Court',
            saveChanges: '💾 Simpan Perubahan', saveSettings: '💾 Simpan Tetapan',
            cancel: 'Batal', delete: 'Hapus', exportCsv: '📥 Eksport CSV',
            shareBookingLink: '🔗 Kongsi Pautan Tempahan Dalam Talian',
            shareTvLink: '📺 Kongsi Pautan TV', shareScoringLink: '📱 Kongsi Pautan Pemarkahan',
            about: 'Tentang', privacy: 'Privasi', terms: 'Syarat', disclaimer: 'Penafian', contact: 'Hubungi',
            builtFor: 'Dibina dengan ❤️ untuk komuniti pickleball Malaysia.',
            contactUs: 'Hubungi Kami', venuePartnerships: 'Perkongsian Venue',
            dataPrivacy: 'Permintaan Privasi Data',
            paymentMethods: 'Butiran Pembayaran (untuk rujukan pelanggan)',
            venueLogo: '🖼️ Logo Venue', financialsAccess: '🔒 Kod Akses Kewangan',
            staffManagement: '👥 Pengurusan Staf', coOwners: '👑 Pemilik Bersama',
            allMethods: 'Semua Kaedah', touchNGo: "🟢 Touch 'n Go", grabPay: '🟢 GrabPay', fpx: '🏦 FPX', cashPayment: '💵 Tunai',
            sendToTnG: "Hantar ke Touch 'n Go", sendToGrabPay: 'Hantar via GrabPay', sendViaFpx: 'Bayar via FPX',
            openPlayFee: 'Fi Drop-in: RM', perPlayer: 'setiap pemain', totalLabel: 'Jumlah:',
            joinQueue: '🎮 Sertai Baris Gilir', openPlayMode: '▶ Open Play', scheduleSession: '📅 Jadual',
            dropInFeeLabel: 'Fi Drop-in (RM)',
            pricePerHr: '/jam', chooseCourt: 'Pilih Court', selectCourt: 'Pilih court yang ingin ditempah.',
            chooseDateTime: 'Pilih Tarikh & Masa', availableSlots: 'Slot tersedia dipaparkan di bawah.',
            fillDetails: 'Isi butiran anda untuk melengkapkan tempahan.',
            allSlotsBooked: 'Semua slot telah ditempah untuk tarikh ini. Cuba tarikh atau court lain.',
            noCourtsAvailable: 'Tiada court tersedia buat masa ini.',
            sendToPayment: 'Hantar ke', referenceNumber: 'Nombor Rujukan *',
            enterRefNum: 'Masukkan nombor rujukan TnG/GrabPay/FPX anda',
            submitPayment: 'Hantar jumlah tepat di atas. Masukkan nombor rujukan selepas pembayaran.',
            selectPaymentMethod: 'Pilih Kaedah Pembayaran:',
            back: '← Kembali', next: 'Seterusnya →', close: '✕ Tutup', done: '✅ Selesai',
            bookAnother: '📅 Tempah Lagi', tryAgain: '🔄 Cuba Lagi',
            paymentPending: 'Pembayaran Dihantar!', waitForConfirmation: 'Jangan tutup halaman ini. Sila tunggu pengesahan dari Admin.',
            bookingConfirmedMsg: 'Tempahan anda telah disahkan.',
            thankYouForBooking: 'Terima kasih kerana menempah dengan kami!',
            showBookingId: 'Sila tunjukkan ID Tempahan', atVenue: 'di venue apabila anda tiba.',
            beEarly: '⏰ Sila ada sekurang-kurangnya 15 minit lebih awal dari jadual tempahan anda.',
            sessionFull: '⚠️ Sesi Penuh', spotsAvailable: '✅ Tempat tersedia — klik untuk menyertai',
            ongoing: '⏳ Sedang Berjalan', joinNow: '▶ Open Play sedang berlangsung — klik untuk menyertai!',
            noUpcomingSessions: 'Tiada sesi Open Play yang dijadualkan buat masa ini.',
            checkBackLater: 'Semak semula kemudian atau hubungi venue.',
            selectSessionToJoin: 'Pilih sesi untuk menyertai. Tidak perlu menempah court tertentu — hanya hadir dan bermain!',
            securedFor: 'Tempat anda dilindungi untuk',
            showTransaction: '📱 Tunjukkan transaksi anda di venue',
            showTransactionNote: 'Tunjukkan butiran transaksi pembayaran semasa mendaftar masuk di venue.',
            seeYouThere: '🎯 Jumpa anda di sana!',
            noPaymentNeeded: 'Tiada pembayaran diperlukan — hanya hadir dan bermain!',
            youAreIn: 'Anda Sudah Masuk!',
            fillAllRequired: 'Isi semua medan yang diperlukan!',
            pleaseSelectCourt: 'Sila pilih court!',
            pleaseSelectTime: 'Sila pilih slot masa!',
            selectPayment: 'Pilih kaedah pembayaran!',
            enterRefRequired: 'Masukkan nombor rujukan pembayaran anda!',
            cantBook: 'Tidak boleh menempah — sesi Open Play sedang berlangsung.',
            slotTaken: 'Maaf, slot masa ini baru sahaja diambil. Sila pilih slot lain.',
            bookingFailed: 'Tempahan gagal disimpan. Sila cuba semula atau hubungi venue.',
            sessionNoLongerAvailable: 'Sesi tidak lagi tersedia.',
            sessionFullOnly: 'Sesi penuh — hanya', spotsLeft: 'tempat tinggal.',
            fillAllFields: 'Isi semua medan.',
            venueNotAvailable: 'Venue tidak tersedia.',
            failedToJoin: 'Gagal menyertai. Sila cuba semula.',
            invalidEmail: 'Masukkan alamat e-mel yang sah.',
            tempEmailNotAllowed: 'E-mel sementara tidak dibenarkan. Sila gunakan alamat e-mel sebenar anda.',
            mustAgree: 'Anda bersetuju dengan Polisi Privasi dan Syarat Perkhidmatan.',
            wrongSomething: 'Ada yang salah: ',
            enterEmailPassword: 'Masukkan e-mel dan kata laluan.',
            fillInAll: 'Isi semua medan.',
            passwordMinLength: 'Kata laluan mesti sekurang-kurangnya 6 aksara.',
            mustAgreeTerms: 'Anda bersetuju dengan Polisi Privasi dan Syarat Perkhidmatan.',
            creatingAccount: 'Mencipta akaun anda...',
            accountCreated: 'Akaun dicipta! Minta pemilik venue menambah e-mel anda dalam Tetapan → Staf atau Pemilik Bersama, kemudian log masuk.',
            sessionExpired: 'Sesi tamat tempoh. Sila daftar semula.',
            submittingVenue: 'Menghantar venue anda...',
            settingThingsUp: 'Menyediakan perkara...',
            loading: 'Memuatkan...',
            demoMode: '🔧 Mod demo — data ditetapkan semula secara berkala',
            tryCourtQ: '🎮 Cuba CourtQ Pro',
            tryDemoDesc: 'Masukkan nama dan e-mel sebenar anda untuk mencuba demo.',
            startDemo: '🎮 Mula Demo',
            settingUpDemo: 'Menyediakan demo anda...',
            demoFailed: 'Demo gagal: ',
            tooManyDemos: 'Terlalu banyak demo aktif sekarang. Sila cuba semula kemudian.',
            venuePendingApproval: 'Venue Menunggu Kelulusan',
            pendingApprovalDesc: 'Venue anda telah dihantar dan sedang menunggu pengesahan. Kami akan memaklumkan anda melalui e-mel apabila ia diaktifkan. Ini biasanya mengambil masa beberapa jam.',
            questionsEmail: 'Soalan? E-mel',
            usedByVenues: '✅ Digunakan oleh venue di seluruh Malaysia',
            integratedPayments: '✅ TnG & GrabPay terintegrasi',
            staffCoowner: '✅ Akaun staf & pemilik bersama',
            regularPrice: 'Biasa', found by: 'Pelanggan Pengasas — 20 pemilik court pertama',
            thenPrice: 'Kemudian', perMo: '/bln',
            courtsIncl: 'court termasuk.',
            forExtraCourts: 'untuk court tambahan',
            forXCourts: 'court',
            freeFor1Month: 'PERCUMA untuk 1 bulan',
            allPremiumFromDay1: '✓ Semua ciri premium termasuk dari Hari 1',
            pricePreviewRate: 'Kadar:', pricePreviewTotal: 'Jumlah:',
            paymentMethod: 'Kaedah Pembayaran', createBooking: '📅 Cipta Tempahan',
            upcoming: 'Akan Datang', today: 'Hari Ini', tomorrow: 'Esok', all: 'Semua',
            checkedIn: 'Didaftar Masuk', pendingConfirmation: 'Menunggu', confirmedStatus: 'Disahkan',
            reviewPending: 'Semak tempahan yang menunggu. Sahkan nombor rujukan pembayaran pelanggan, kemudian sahkan.',
            accessCodeRequired: 'Kod Akses Diperlukan', enterAccessCode: 'Masukkan kod akses pemilik untuk melihat kewangan.',
            unlock: '🔓 Buka', lock: '🔒 Kunci',
            bookingsLabel: 'Tempahan', utilization: 'Penggunaan', cancelledLabel: '% dibatalkan',
            prevLabel: 'sebelum:', peakHours: '⏰ Waktu Puncak', netPosition: '💰 Posisi Bersih',
            monthlyNet: '📅 Posisi Bersih Bulanan', expenses: '📋 Perbelanjaan',
            transactions: '📊 Transaksi', detailedBreakdown: '📈 Butiran Terperinci',
            playerRetention: '👥 Pengekalan Pemain', repeatPlayers: 'Pemain Berulang',
            newPlayers: 'Pemain Baharu', topLoyal: '🏅 10 Pemain Setia Teratas',
            allTime: 'Semua Masa', thisMonth: 'Bulan Ini', thisWeek: 'Minggu Ini',
            totalVenues: 'Jumlah Venue', activeContracts: 'Kontrak Aktif',
            monthlyRetainers: 'Retainer Bulanan', totalDue: 'Jumlah Belum Bayar',
            devDashboard: '💻 Papan Pemuka Dev', freeTierMonitor: '📊 Pemantauan Tier Percuma',
            liveDemoActivity: '🎮 Aktiviti Demo Langsung', ownerEmails: '📧 E-mel Pemilik',
            demoLeads: '📋 Utusan Demo', announcements: '📢 Pengumuman',
            newTournament: '🏆 Kejohanan Baharu', tournamentName: 'Nama Kejohanan',
            format: 'Format', playersTeams: 'Pemain / Pasukan (satu per baris, min 4)',
            playersPerGroup: 'Pemain Per Kumpulan', eliminationStart: 'Pusingan Permulaan Penyingkiran',
            advanceFromGroups: 'Majdar dari Kumpulan', courtsToUse: 'Court Untuk Digunakan',
            createTournament: '🏆 Cipta Kejohanan',
            roundRobinSetup: '🔄 Persediaan Round Robin',
            startRoundRobin: '▶ Mula Round Robin',
            aiResponse: '🔮 AI', monthlyRetainerLabel: 'Retainer Bulanan (RM)',
            addPayment: '💰 Tambah Pembayaran', transactionNumber: 'Nombor Transaksi',
            dueDate: 'Tarikh Akhir', paidAt: 'Dibayar Pada', savePayment: '💾 Simpan Pembayaran',
            startOpenPlay: '▶ Mula Sesi Open Play',
            startDate: 'Tarikh Mula', endDate: 'Tarikh Tamat', startTime: 'Masa Mula', endTime: 'Masa Tamat',
            rotation: 'Putaran (minit)', assignCourts: 'Tugaskan Court',
            scheduleOpenPlay: '📅 Jadual Open Play', maxPlayers: 'Pemain Maksimum',
            fourOnFour: '4 Masuk / 4 Keluar', winnersSplit: 'Pemenang Kekal & Bahagi', roundRobin: 'Round Robin',
            loopingMode: '🔄 Mod Berulang', afterGame: 'Selepas permainan, semua pemain kembali ke baris gilir',
            addToQueue: '➕ Tambah Pemain', startNow: '▶ Mula Sekarang', cancelSession: '✕ Batal',
            groupName: 'Nama Kumpulan (pilihan)', joinQueueAs: 'Sertai Sebagai',
            havePartner: '👫 Saya ada rakan', needPartner: '🙋 Saya perlu rakan',
            partnerName: 'Nama Rakan', fixedTeammates: '🔒 Rakan tetap (kekalkan setiap pusingan)',
            skillLevel: 'Tahap Kemahiran', beginner: 'Pemula', intermediate: 'Pertengahan',
            advanced: 'Lanjutan', pro: 'Pro',
            bookingDetails: '📅 Butiran Tempahan', recordResult: '🏆 Rekod Keputusan',
            checkIn: '✅ Daftar Masuk', editPlayers: '✏️ Edit Pemain',
            archiveOldData: '📦 Arkib Data Lama', archiveDesc: 'Arkib tempahan dan jualan lebih tua daripada tarikh pemotongan. Data yang diarkib akan dimuat turun sebagai CSV kemudian dibuang dari Firestore untuk menjimatkan ruang.',
            cutoffDate: 'Tarikh Pemotongan (arkib semua sebelum tarikh ini)', irreversible: '⚠️ Tidak Boleh Dikembalikan',
            emailCampaign: '📧 Kempen E-mel', postAnnouncement: '📢 Siar',
            confirmAction: '⚠️ Sahkan', confirmClear: '🗑️ Hapus',
            addNewCourt: '🏗️ Tambah Court Baharu', courtName: 'Nama Court',
            location: 'Lokasi', surface: 'Permukaan', environment: 'Persekitaran',
            outdoor: 'Luar', indoor: 'Dalam', color: 'Warna',
            descriptionNotes: 'Penerangan / Nota', addCourtBtn: '➕ Tambah Court',
            editCourtTitle: '✏️ Edit Court', saveChangesBtn: '💾 Simpan Perubahan',
            removeCourtTitle: '🗑️ Buang Court', removeCourtBtn: 'Buang Court',
            venueManagement: 'Pengurusan Venue', courtSchedule: '📅 Jadual Court',
            conflicts: '⚠️ Konflik', newBookingAdmin: '📅 Tempahan Baharu (Admin)',
            customer: 'Pelanggan', fullName: 'Nama penuh', court: 'Court', date: 'Tarikh',
            duration: 'Tempoh', oneHour: '1 jam', twoHours: '2 jam', threeHours: '3 jam',
            lessonClinic: 'Kelas/Klinik', namesComma: 'Nama dipisahkan koma',
            filterUpcoming: 'Akan Datang', filterAll: 'Semua',
            selectCourtLabel: 'Pilih court...', rate: 'Kadar:', totalLabel2: 'Jumlah:',
            accessCode: 'Kod Akses (4-6 digit)', shareWithOwner: 'Kongsi kod ini dengan pemilik venue untuk mengakses halaman Kewangan.',
            logoUrl: 'URL Gambar Logo', logoHint: 'Tampal URL awam ke gambar logo anda. Saiz yang disyorkan: 200x200px atau lebih kecil.',
            staffAccessNote: 'Staf boleh mengakses papan pemuka tetapi bukan Kewangan atau Tetapan.',
            coownerNote: 'Pemilik bersama mempunyai akses penuh — Kewangan, Tetapan, Pengesahan, dan semua ciri papan pemuka.',
            add: '+ Tambah', pendingVerification: '⏳ Menunggu Pengesahan',
            monthlyFee: 'Fi Bulanan', ackReceipt: '📋 Resit Pengesahan',
            receiptNum: 'Nombor Resit', owner: 'Pemilik', status: 'Status',
        }
    }
};

// Helper functions
function cqFormatCurrency(amount) {
    return CQ_CONFIG.currency.symbol + Number(amount || 0).toLocaleString();
}
function cqNow() {
    const d = new Date();
    return new Date(d.getTime() + (d.getTimezoneOffset() + CQ_CONFIG.utcOffset) * 60000);
}
function cqTodayISO() {
    const d = cqNow();
    return d.toISOString().split('T')[0];
}
function cqTimeStr() {
    return new Date().toLocaleString('en-US', { timeZone: CQ_CONFIG.timezone });
}
let _cqLang = localStorage.getItem('cqLang') || 'en';
function t(key) {
    return (CQ_CONFIG.translations[_cqLang] && CQ_CONFIG.translations[_cqLang][key]) || CQ_CONFIG.translations.en[key] || key;
}
function setLang(lang) {
    _cqLang = lang;
    localStorage.setItem('cqLang', lang);
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        el.textContent = t(key);
    });
    document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
        el.placeholder = t(el.getAttribute('data-i18n-placeholder'));
    });
}
